/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--surface-bright)",
        "surface-dim": "var(--surface-dim)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-high": "var(--surface-container-high)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-error-container": "var(--on-error-container)",
        "surface": "var(--surface)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary": "var(--on-tertiary)",
        "background": "var(--background)",
        "on-primary": "var(--on-primary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "inverse-primary": "var(--inverse-primary)",
        "inverse-surface": "var(--inverse-surface)",
        "error": "var(--error)",
        "on-background": "var(--on-background)",
        "primary-fixed": "var(--primary-fixed)",
        "error-container": "var(--error-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-variant": "var(--surface-variant)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "primary": "var(--primary)",
        "on-secondary": "var(--on-secondary)",
        "secondary": "var(--secondary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "outline-variant": "var(--outline-variant)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "secondary-container": "var(--secondary-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-tint": "var(--surface-tint)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container": "var(--surface-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-surface": "var(--on-surface)",
        "outline": "var(--outline)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "tertiary": "var(--tertiary)",
        "on-error": "var(--on-error)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "container-padding": "2rem",
        "stack-sm": "0.5rem",
        base: "4px",
      },
      fontFamily: {
        h1: ["Inter"],
        code: ["ui-monospace"],
        h2: ["Inter"],
        "label-caps": ["Space Grotesk"],
        body: ["Inter"],
        inter: ["Inter"],
      },
      fontSize: {
        h1: ["3rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        code: ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        h2: ["1.875rem", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.05em", fontWeight: "600" }],
        body: ["1rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
