/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#31394d",
        "surface-dim": "#0b1326",
        "on-secondary-container": "#00344e",
        "surface-container-low": "#131b2e",
        "surface-container-high": "#222a3d",
        "secondary-fixed": "#c9e6ff",
        "on-error-container": "#ffdad6",
        "surface": "#0b1326",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-container-lowest": "#060e20",
        "on-tertiary": "#3c0091",
        "background": "#0b1326",
        "on-primary": "#1000a9",
        "on-secondary-fixed": "#001e2f",
        "primary-container": "#8083ff",
        "inverse-primary": "#494bd6",
        "inverse-surface": "#dae2fd",
        "error": "#ffb4ab",
        "on-background": "#dae2fd",
        "primary-fixed": "#e1e0ff",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#340080",
        "primary": "#c0c1ff",
        "on-secondary": "#00344d",
        "secondary": "#89ceff",
        "inverse-on-surface": "#283044",
        "surface-container-highest": "#2d3449",
        "outline-variant": "#464554",
        "on-secondary-fixed-variant": "#004c6e",
        "secondary-container": "#00a2e6",
        "secondary-fixed-dim": "#89ceff",
        "surface-tint": "#c0c1ff",
        "tertiary-container": "#a078ff",
        "surface-container": "#171f33",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#dae2fd",
        "outline": "#908fa0",
        "on-tertiary-fixed": "#23005c",
        "tertiary": "#d0bcff",
        "on-error": "#690005",
        "tertiary-fixed": "#e9ddff",
        "on-primary-container": "#0d0096",
        "primary-fixed-dim": "#c0c1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "container-padding": "2rem",
        "stack-sm": "0.5rem",
        base: "4px",
      },
      fontFamily: {
        h1: ["Inter"],
        code: ["ui-monospace"],
        h2: ["Inter"],
        "label-caps": ["Space Grotesk"],
        body: ["Inter"],
        inter: ["Inter"],
      },
      fontSize: {
        h1: ["3rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        code: ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        h2: ["1.875rem", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.05em", fontWeight: "600" }],
        body: ["1rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
