import Icon from "../components/Icon";

export default function Privacy() {
  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 lg:space-y-8 font-inter text-slate-300">
      <section className="flex flex-col gap-2 border-b border-white/5 pb-6">
        <h1 className="font-h1 text-3xl font-extrabold text-white tracking-tight">
          Privacy &amp; Data Policy
        </h1>
        <p className="text-slate-400 max-w-2xl text-sm leading-relaxed">
          Official policy regarding data collection, processing, and biometric template storage for this academic research application.
        </p>
      </section>

      <div className="max-w-4xl grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Core Principles */}
        <div className="glass-panel p-6 rounded-xl space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400">
              <Icon name="school" />
            </div>
            <h2 className="text-lg font-bold text-white">Academic Project Scope</h2>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            This system is developed as an academic biometrics research project for the <strong>MSC-UPEC (2nd Semester) Facial Biometrics course</strong>. 
            All functionalities, including face detection, template matching, and error-rate analysis, are created strictly for educational demonstration and performance evaluation.
          </p>
        </div>

        {/* Local Processing */}
        <div className="glass-panel p-6 rounded-xl space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-emerald-500/10 flex items-center justify-center text-emerald-400">
              <Icon name="security" />
            </div>
            <h2 className="text-lg font-bold text-white">Biometric Data Processing</h2>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            All facial analysis, alignment, and feature extraction are executed <strong>locally</strong> on the self-hosted FastAPI backend. No face crops, original images, or mathematical templates are transmitted to external servers or third-party providers.
          </p>
        </div>

        {/* Templates */}
        <div className="glass-panel p-6 rounded-xl space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-cyan-500/10 flex items-center justify-center text-cyan-400">
              <Icon name="fingerprint" />
            </div>
            <h2 className="text-lg font-bold text-white">Biometric Templates</h2>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Enrolled subjects are represented solely as mathematical vectors (embeddings) generated by the FaceNet (InceptionResnetV1) model. 
            These templates contain no visual pixels, cannot be reconstructed back into face images, and are stored in simple local JSON files for matching.
          </p>
        </div>

        {/* Compliance */}
        <div className="glass-panel p-6 rounded-xl space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400">
              <Icon name="gavel" />
            </div>
            <h2 className="text-lg font-bold text-white">Standard Datasets</h2>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            For evaluation, the system incorporates the open-source <strong>Labeled Faces in the Wild (LFW)</strong> benchmark dataset. 
            All subjects downloaded for the performance evaluation are public figures from public benchmarks, complying with academic research citation guidelines.
          </p>
        </div>
      </div>

      {/* Footer Disclaimer */}
      <div className="max-w-4xl p-5 bg-indigo-500/5 border border-indigo-500/10 rounded-xl flex items-start gap-4">
        <Icon name="info" className="text-indigo-400 text-xl shrink-0 mt-0.5" />
        <div>
          <h4 className="text-sm font-semibold text-white">Academic Compliance Note</h4>
          <p className="text-xs text-slate-400 mt-1 leading-relaxed">
            This project is strictly non-commercial. If you wish to delete your custom enrolled data or registered templates, 
            you can do so instantly using the "Delete" utility inside the Enrollment page, which completely wipes all corresponding files from disk.
          </p>
        </div>
      </div>
    </div>
  );
}
